<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Email or Password is not correct.' => '邮箱或密码不正确',
    'Account' => '账户',
    'Created' => '创建时间',
    'Description' => '描述',
    'Email' => '邮箱',
    'Encrypt Password' => '加密的密码',
    'ID' => '序号',
    'Name' => '名称',
    'Password' => '密码',
    'Public Key' => '公钥',
    'Salt' => '加密随机数',
    'Token' => 'token',
    'Uid' => '用户ID',
    'Updated' => '更新时间',
    'Web Link' => '网址',
];
