<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accounts' => '账户',
    'Apply' => '应用',
    'Download' => '下载',
    'Edit' => '编辑',
    'Generate' => '生成',
    'Generate a public key' => '生成公钥',
    'Home' => '首页',
    'Log In' => '登陆',
    'Log out' => '登出',
    'Login' => '',
    'New Account' => '新账户',
    'Password Manager' => '密码管理',
    'Private Key' => '私钥',
    'Public Key' => '公钥',
    'Register' => '注册',
    'Remove' => '移除',
    'Save' => '保存',
    'Save And Return' => '保存并返回',
    'Show Password' => '显示密码',
    'The private key is VERY important. It is used to decrypt the password. Please save it careful.' => '私钥是非常重要的。它是用来解密密码。请保存它小心.',
    'Upload a private key' => '上传私钥',
];
